"""
core/mailer.py — Email via Flask-Mail
MEDIUM #8 — Monthly reports via email

.env variables:
  MAIL_SERVER=smtp.gmail.com
  MAIL_PORT=587
  MAIL_USERNAME=your@gmail.com
  MAIL_PASSWORD=your_app_password_16chars
  MAIL_DEFAULT_SENDER=your@gmail.com

Install: pip install flask-mail
"""

import os

MAIL_SERVER  = os.getenv('MAIL_SERVER',  'smtp.gmail.com')
MAIL_PORT    = int(os.getenv('MAIL_PORT', 587))
MAIL_USERNAME= os.getenv('MAIL_USERNAME', '')
MAIL_PASSWORD= os.getenv('MAIL_PASSWORD', '')
MAIL_SENDER  = os.getenv('MAIL_DEFAULT_SENDER', MAIL_USERNAME)


def configure_mail(app):
    """Call this in app.py after creating Flask app."""
    app.config['MAIL_SERVER']          = MAIL_SERVER
    app.config['MAIL_PORT']            = MAIL_PORT
    app.config['MAIL_USE_TLS']         = True
    app.config['MAIL_USERNAME']        = MAIL_USERNAME
    app.config['MAIL_PASSWORD']        = MAIL_PASSWORD
    app.config['MAIL_DEFAULT_SENDER']  = MAIL_SENDER


def send_monthly_report(to_email, lot_name, month, pdf_bytes):
    """
    Send monthly revenue report PDF via email.
    Returns (success, message)
    """
    if not MAIL_USERNAME or not MAIL_PASSWORD:
        return False, 'Email not configured — add MAIL_USERNAME and MAIL_PASSWORD to .env'

    try:
        from flask_mail import Mail, Message
        from flask import current_app
        mail = Mail(current_app)

        msg = Message(
            subject=f'{lot_name} — Monthly Revenue Report — {month}',
            recipients=[to_email],
            body=(
                f'Dear Lot Owner,\n\n'
                f'Please find attached your monthly revenue report for {month}.\n\n'
                f'Lot: {lot_name}\n'
                f'Period: {month}\n\n'
                f'This report was automatically generated by Smart Parking System.\n\n'
                f'Regards,\n'
                f'Smart Parking System'
            )
        )

        if pdf_bytes:
            msg.attach(
                filename=f'report_{month}.pdf',
                content_type='application/pdf',
                data=pdf_bytes
            )

        mail.send(msg)
        return True, 'Email sent successfully'

    except ImportError:
        return False, 'flask-mail not installed — run: pip install flask-mail'
    except Exception as e:
        return False, str(e)